### PR TITLE
Resolve akka versions explicitly to unblock build.

### PR DESCRIPTION
**Pull request by falkzoll**
- An akka upgrade in apache/openwhisk required changes here to successfully build and run the test cases.

### CODE REVIEW

**Comment by falkzoll** [comment]
Closing/Opening PR to force re-check in travis.

**Comment by falkzoll** [comment]
Two tests are still failing. Checked the travis build logs and they fail since longer time already.

`runtime.actionContainers.PythonActionLoopContainerTests > actionloop-python-v3.7 should run zipped Python action containing a virtual environment FAILED`
`runtime.actionContainers.PythonActionLoopContainerTests > actionloop-python-v3.7 should run zipped Python action containing a virtual environment with non-standard entry point FAILED`

I will try to find the root cause for them to get the build unblocked again.
In the meantime I will close this PR. Will open it again, when I have an update.

**Comment by falkzoll** [comment]
The python package `random-useragent` has been removed from pypi.org. This package is used in as sample in some of the test cases. Updated the test actions to use the similar package random_user_agent package.

**Review by rabbah — APPROVED** [review]

**Comment by sciabarracom** [comment]
I included it in #111 (it was necessary) with lot of rework of the tests

**Comment by falkzoll** [comment]
Closing this PR as its content is included in the now merged PR #111 .

**Pull request closed without merging**
